name: Print File Content CI/CD
on: [push, pull_request]
jobs:
  Print_Content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: |
          cat hello_world.txt
